version: "3.3"
services:
  hub:
    image: selenium/hub:3.141.59
    container_name: hub
    ports:
      - "4444:4444"

  chrome1:
    image: selenium/node-chrome:3.141.59
    container_name: web-chrome1
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080
      TZ: Asia/Jerusalem
    volumes:
      - ./:./
    ports:
      - "5901:5900"
    links:
      - hub

  flask:
    image: flask-image:latest
    container_name: flask-server
    depends_on:
      - hub
    ports:
      - "5000:5000"
